name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    uses: centralnicgroup-opensource/rtldev-middleware-shareable-workflows/.github/workflows/release.yml@main
    secrets: inherit
    with:
      repository: ${{ github.repository }}